# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

jobs:
- job: build
  displayname: build middleware and sample
  pool: 
    vmImage: 'ubuntu-latest'
  steps:
  - script: dotnet build ./Xstof.RequestGrid/Xstof.RequestGrid.csproj $(buildConfiguration)
    displayName: 'build Xstof.RequestGrid.csproj in config: $(buildConfiguration)'
  - script: dotnet build ./Xstof.RequestGrid.Sample/Xstof.RequestGrid.Sample.csproj $(buildConfiguration)
    displayName: 'build Xstof.RequestGrid.Sample.csproj in config: $(buildConfiguration)'
