# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'

jobs:
- job: build
  displayName: build middleware and sample
  pool: 
    vmImage: 'ubuntu-latest'
  steps:
  - script: dotnet build -c $(buildConfiguration) ./Xstof.RequestGrid/Xstof.RequestGrid.csproj
    displayName: 'build Xstof.RequestGrid.csproj in config: $(buildConfiguration)'
  - script: dotnet build -c $(buildConfiguration) ./Xstof.RequestGrid.Sample/Xstof.RequestGrid.Sample.csproj
    displayName: 'build Xstof.RequestGrid.Sample.csproj in config: $(buildConfiguration)'
